# - name: "install node js"
#   shell: |
#     curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
#     sudo apt -y upgrade
#     sudo apt install -y nodejs

# - name: "install pm2 by npm"
#   become: true
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present

- name: "copy files from CircleCI to server"
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu


- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    npm install